
[build]
builder = "NIXPACKS"
buildCommand = "npm run build"
watchPatterns = ["**/*.ts", "**/*.tsx", "**/*.js", "**/*.jsx"]

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/health"
healthcheckTimeout = 100

[[services]]
name = "backend"
source = "server"

[[services]]
name = "frontend" 
source = "."
