
[build]
builder = "NIXPACKS"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"

[[services]]
name = "backend"
source = "server"

[[services]]
name = "frontend" 
source = "."
